apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: cert-manager-webhook
spec:
  forProvider:
    chart:
      name: cert-manager-webhook-duckdns
      repository: oci://madou-scientistou.duckdns.org/certmanager-duckdns-webhook-oci
      version: v1.2.3
    namespace: cert-manager
    values:
      duckdns:
        token: "79f4e377-2623-45f7-81e0-f8f4d07a466c"
      clusterIssuer:
        production:
          create: true
        staging:
          create: true
        email: achrefbenmbarekopensource@gmail.com
      logLevel: 2
  providerConfigRef:
    name: helm-provider
