apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: nginx-ingress-controller
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: nginx-ingress-controller
      repository: https://charts.bitnami.com/bitnami
      version: 11.5.4
#     pullSecretRef:
#       name: museum-creds
#       namespace: default
#     url: "https://charts.bitnami.com/bitnami/wordpress-9.3.19.tgz"
    namespace: nginx-ingress
  providerConfigRef:
    name: helm-provider

