apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: duckdns-webhook-token-secret
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: duckdns-webhook-token
  data:
    - secretKey: token
      remoteRef:
        key: secret/duckdns-webhook-token
        property: token

